# Generated by Django 2.2 on 2020-07-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('promo_code', models.CharField(max_length=10)),
                ('expiration_date', models.DateTimeField()),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Promo')),
            ],
        ),
    ]
