# Generated by Django 2.2 on 2020-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='promocodestorage',
            name='promo_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='promocodestorage',
            index=models.Index(fields=['promo', 'email'], name='main_promoc_promo_i_7ff1ee_idx'),
        ),
    ]
