# Generated by Django 2.2 on 2020-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200701_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
